"""application answers

Revision ID: d615608fe7ce
Revises: 974bafd70d13
Create Date: 2026-08-01 15:27:24.074450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd615608fe7ce'
down_revision: Union[str, Sequence[str], None] = '974bafd70d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_offer_id', sa.Integer(), nullable=False),
    sa.Column('tell_me_about_yourself', sa.Text(), nullable=False),
    sa.Column('why_this_company', sa.Text(), nullable=False),
    sa.Column('why_should_we_hire_you', sa.Text(), nullable=False),
    sa.Column('greatest_strength', sa.Text(), nullable=False),
    sa.Column('greatest_weakness', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_offer_id'], ['job_offers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_offer_id')
    )
    op.create_index(op.f('ix_application_answers_id'), 'application_answers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_answers_id'), table_name='application_answers')
    op.drop_table('application_answers')
    # ### end Alembic commands ###
