"""interview preparation

Revision ID: e061e146ceb5
Revises: d615608fe7ce
Create Date: 2026-08-01 15:53:24.544179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e061e146ceb5'
down_revision: Union[str, Sequence[str], None] = 'd615608fe7ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_preparation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_offer_id', sa.Integer(), nullable=False),
    sa.Column('technical_questions', sa.JSON(), nullable=False),
    sa.Column('behavioral_questions', sa.JSON(), nullable=False),
    sa.Column('tips', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_offer_id'], ['job_offers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_offer_id')
    )
    op.create_index(op.f('ix_interview_preparation_id'), 'interview_preparation', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_preparation_id'), table_name='interview_preparation')
    op.drop_table('interview_preparation')
    # ### end Alembic commands ###
